name = "storybakery/pesde_gitrev"
version = "0.1.5"
repository = "https://github.com/StoryBakery/pesde-gitrev"
license = "MIT"
includes = ["pesde.toml", "src/**"]

[target]
environment = "lune"
bin = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
