name = "storybakery/pesdekery"
version = "0.0.0"
repository = "https://github.com/StoryBakery/pesdekery"
license = "MIT"
includes = ["pesde.toml", "src/**"]

[target]
environment = "lune"
bin = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
